default: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  host:     <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *defaults
  adapter: postgresql
  database: ficha_avaliacao_dev

staging:
  <<: *defaults
  adapter: postgresql
  database: ficha_avaliacao_stag

test:
  <<: *defaults
  adapter: postgresql
  database: ficha_avaliacao_test

production:
  <<: *defaults
  adapter: postgresql
  database: ficha_avaliacao_prod